spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # show_sql : `System.out` 에 하이버네이트 실행 SQL을 남긴다
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # org.hibernate.SQL : logger를 통해 하이버네이트 실행 SQL을 남긴다.
#  org.hibernate.type: trace # SQL  실행 파라미터를 로그로 남긴다.